# Generated by Django 2.2.1 on 2019-06-03 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='mob',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='passw',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='user',
            new_name='username',
        ),
    ]
