# Generated by Django 2.2.1 on 2019-06-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190604_0746'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
